# Generated by Django 3.1.2 on 2020-10-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.IntegerField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=30)),
                ('ano', models.IntegerField(max_length=4)),
                ('modelo', models.CharField(max_length=11)),
                ('cor', models.CharField(max_length=12)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
    ]
